sudo: required
services:
    - docker
before_install:
    - docker build -t edoatley/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true edoatley/react-test npm test
after_success:
    - docker build -t edoatley/multi-client ./client
    - docker build -t edoatley/multi-nginx ./nginx
    - docker build -t edoatley/multi-server ./server
    - docker build -t edoatley/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push edoatley/multi-client
    - docker push edoatley/multi-nginx
    - docker push edoatley/multi-server
    - docker push edoatley/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: docker-multi
    env: DockerMulti-env
    edge: true
    bucket_name: "elasticbeanstalk-us-east-1-705251932900"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
 