sudo: required
services:
    - docker
before_install:
    - docker build -t eoatley/react-test -f ./client/Dockerfile.dev
script:
    - docker run -e CI=true eoatley/react-test npm test
after_success:
    - docker build -t eoatley/multi-client ./client
    - docker build -t eoatley/multi-nginx ./nginx
    - docker build -t eoatley/multi-server ./server
    - docker build -t eoatley/multi-worker ./worker